added solution - hash
glones/servlet-project pull request #11
Opened 2020-09-29 15:35 UTC by glones

2020-09-29 16:39 UTC, voloshynamaryna11 reviewed
good

2020-09-29 16:39 UTC, voloshynamaryna11 commented on src/main/resources/init_db.sql
> +ADD COLUMN `salt` VARBINARY(16) NOT NULL AFTER `password`;
лучше просто добавь в таблицу новый столбец

2020-09-29 17:34 UTC, KseniiaMakarova requested changes

2020-09-29 17:34 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/util/HashUtil.java
> +            throw new RuntimeException("Problem with password hashing");
```suggestion
            throw new RuntimeException("Problem with password hashing", e);
```

2020-09-29 17:34 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +ADD COLUMN `salt` VARBINARY(16) NOT NULL AFTER `password`;
I agree, let's better modify CREATE statement

also, I see that you are inserting users here
let's do this in injectDataController (you should insert salt to DB as well)

2020-09-29 21:35 UTC, glones commented on src/main/resources/init_db.sql
> +ADD COLUMN `salt` VARBINARY(16) NOT NULL AFTER `password`;
done

2020-09-29 21:35 UTC, glones commented on src/main/java/com/internet/shop/util/HashUtil.java
> +            throw new RuntimeException("Problem with password hashing");
done

2020-09-30 06:43 UTC, KseniiaMakarova approved these changes

2020-10-15 11:56 UTC, merged